export default {
  AHEAD_BANCORP_ELECTRONIC_COMMUNICATIONS_AGREEMENT:
    'AHEAD_BANCORP_ELECTRONIC_COMMUNICATIONS_AGREEMENT',
  AHEAD_BANCORP_DEPOSIT_ACCOUNT_AGREEMENT: 'AHEAD_BANCORP_DEPOSIT_ACCOUNT_AGREEMENT',
  AHEAD_BANCORP_BANK_CARDHOLDER_AGREEMENT: 'AHEAD_BANCORP_BANK_CARDHOLDER_AGREEMENT',
  BANCORP_BANK_PRIVACY_NOTICE: 'BANCORP_BANK_PRIVACY_NOTICE',
  AHEAD_PRIVACY_POLICY: 'AHEAD_PRIVACY_POLICY',
  AHEAD_USER_AGREEMENT: 'AHEAD_USER_AGREEMENT',
};
