export default {
  navigationKey: {
    user: 'User',
    guest: 'Guest',
  },
  auth: {
    welcome: 'Welcome Screen',
    signIn: 'Sign In Screen',
    signUpMail: 'Sign Up Mail Screen',
    signUpMailVerification: 'Sign Up Mail Verification Screen',
    signUpPassword: 'Sign Up Password Screen',
    signUpName: 'Sign Up Name Screen',
    signUpBirthDate: 'Sign Up Birth Date Screen',
    signUpPhone: 'Sign Up Phone Screen',
    signUpAddressSuggestion: 'Sign Up Address Suggestion Screen',
    signUpAddress: 'Sign Up Address Screen',
    signUpPhoneConfirmation: 'Sign Up Phone Confirmation Code Screen',
    signUpSSN: 'Sign Up SSN Screen',
    legalAgreement: 'Sign Up Legal Agreement Screen',
    welcomeToKinly: 'Welcome to Kinly Screen',
    fund: 'Sign Up Fund Screen',
    fundChoice: 'Sign Up Fund Choice Screen',
    depositCash: 'Sign Up Sign Up Deposit Cash Screen',
    forgotPassword: 'Forgot Password Screen',
  },
  home: {
    stack: 'Home Stack',
    main: 'Home Screen',
  },
  accounts: {
    stack: 'Accounts Stack',
    main: 'Accounts Screen',
    accountDetails: 'Account Details Screen',
    transactions: 'Transactions List Screen',
    linkCard: 'Link Card Screen',
    linkDebitCardPage: 'Link Debit Screen',
    takeOutMoney: 'Take Out Money Screen',
  },
  card: {
    stack: 'Card Stack',
    main: 'Card Screen',
    activateCard: 'Activate Card',
    securityCheck: 'Security Check Card',
    setDebitCardPinInfo: 'Set Debit Card Pin Info Screen',
    setDebitCardPinForm: 'Set Debit Card Pin Screen',
    setDebitCardPinSuccess: 'Set Debit Card Pin Success Screen',
    activateSuccess: 'Activate Card Success Screen',
  },
  finEd: {
    stack: 'FinEd Stack',
    main: 'FinEd Screen',
    welcome: 'Welcome Screen',
  },
  settings: {
    main: 'Settings Menu',
    statements: 'Statements List Screen',
    statementDetails: 'Statement Details Screen',
    accountPolicy: 'Account Policy Screen',
    accountPolicyDetails: 'Account Policy Details Screen',
    userInfo: 'User Info Screen',
    updateEmail: 'Update Email Screen',
    updateAddress: 'Update Address Screen',
    updateCity: 'Update City Screen',
    accountInfo: 'Account Info Screen',
    about: 'About Screen',
    contact: 'Contact Screen',
    changePassword: 'Change Password Screen',
    marketplace: 'Marketplace Screen',
  },
  shared: {
    directDepositFormView: 'Direct Deposit Form Screen',
    earlyPaycheckSuccess: 'Early Paycheck Success Screen',
    addMoney: 'Add Money Screen',
    earlyPaycheck: 'Early Paycheck Screen',
    main: 'Tab Bar',
    moneyTransferSuccess: 'Money Transfer Success Screen',
    overdraftSell: 'Overdraft Sell Screen',
    overdraftLegalAgreement: 'Overdraft Legal Agreement Screen',
    overdraftOptInSuccess: 'Overdraft Opt In Success Screen',
    phoneNumber: 'Phone Number Screen',
    phoneNumberConfirmation: 'Phone Number Confirmation Screen',
  },
  marketplace: {
    directPartner: 'Direct Partner Screen',
  },
};
