import { ICONS } from '_constants';

export const MarketplaceStaticData = [
  {
    name: 'Fiona Auto',
    shortDescription: `Fiona is the fastest and easiest way to search financial service offers. From loans to credit cards & more-get offers you need.`,
    icon: ICONS.fiona,
    url: 'https://fiona.com/partner/first-boulevardalr/loans',
    title: 'Finance made friendly',
    logo: ICONS.fionaLogo,
    banner: require('_assets/MarketplaceBanners/fiona.png'),
    longDescription: `Fiona is the fastest, easiest, and most comprehensive way to search financial service offers from top providers. Fiona is created and powered by Even, the leading search, comparison and recommendation engine for financial services. Find a financial product that fits your needs. Just answer a few questions and Fiona matches you with offers from their network of lenders. `,
  },
  {
    name: 'Fiona Student Loans',
    shortDescription: `Fiona is the fastest and easiest way to search financial service offers. From loans to credit cards & more-get offers you need.`,
    icon: ICONS.fiona,
    url: 'https://fiona.com/partner/firstboulevardslr/loans',
    title: 'Finance made friendly',
    logo: ICONS.fionaLogo,
    banner: require('_assets/MarketplaceBanners/fiona.png'),
    longDescription: `Fiona is the fastest, easiest, and most comprehensive way to search financial service offers from top providers. Fiona is created and powered by Even, the leading search, comparison and recommendation engine for financial services. Find a financial product that fits your needs. Just answer a few questions and Fiona matches you with offers from their network of lenders. `,
  },
  {
    name: 'Fiona Person Loans',
    shortDescription: `Fiona is the fastest and easiest way to search financial service offers. From loans to credit cards & more-get offers you need.`,
    icon: ICONS.fiona,
    url: 'https://fiona.com/partner/firstboulevardpl/loans',
    title: 'Finance made friendly',
    logo: ICONS.fionaLogo,
    banner: require('_assets/MarketplaceBanners/fiona.png'),
    longDescription: `Fiona is the fastest, easiest, and most comprehensive way to search financial service offers from top providers. Fiona is created and powered by Even, the leading search, comparison and recommendation engine for financial services. Find a financial product that fits your needs. Just answer a few questions and Fiona matches you with offers from their network of lenders. `,
  },
  {
    name: 'Fiona Credit Cards',
    shortDescription: `Fiona is the fastest and easiest way to search financial service offers. From loans to credit cards & more-get offers you need.`,
    icon: ICONS.fiona,
    url: 'https://fiona.com/partner/firstboulevardcc/credit-cards',
    title: 'Finance made friendly',
    logo: ICONS.fionaLogo,
    banner: require('_assets/MarketplaceBanners/fiona.png'),
    longDescription: `Fiona is the fastest, easiest, and most comprehensive way to search financial service offers from top providers. Fiona is created and powered by Even, the leading search, comparison and recommendation engine for financial services. Find a financial product that fits your needs. Just answer a few questions and Fiona matches you with offers from their network of lenders. `,
  },
  {
    name: 'Amplify',
    shortDescription: `We offer life insurance policies that help protect your loved ones and grow tax-free wealth to use while you're alive.`,
    icon: ICONS.amplify,
    url: 'https://beamplify.com/landing/vul-flexible-investments-kinly',
    title: 'Life Insurance for Building Wealth',
    logo: ICONS.amplifyLogo,
    banner: require('_assets/MarketplaceBanners/amplify.png'),
    longDescription: `At Amplify, we believe that securing our future, protecting our families, and growing our wealth should be a transparent and inclusive opportunity – for everyone. We’ re democratizing access to life insurance policies previously used by the wealthiest 1%. These products protect your family and allow you to build and access tax- free growth while you're still alive. We help you customize a plan based on your needs and get pre-underwritten for the best rates, all in under 5 minutes. We have a team of live, licensed experts to help you at any time.`,
  },
  {
    name: 'Better Mortgage, Inc.',
    shortDescription: `***$500 closing cost credit for purchase or refi*** You could save time and money with a simple, digital-first Better Mortgage experience. With everyday low pricing, a transparent process, and a single platform for everything.`,
    icon: ICONS.better,
    url: 'https://better.com/b/kinly',
    title: '',
    logo: ICONS.betterLogo,
    banner: require('_assets/MarketplaceBanners/better.png'),
    longDescription: `We believe homeownership should be fast, transparent, and low-cost. For everyone. Homeownership is a huge part of our economy. Housing overall is a $33 trillion business, and mortgages account for $15 trillion. Yet home finance operates in the same way it has for decades — through opaque systems and expensive intermediaries whose interests are misaligned with consumers’. That’s why Better.com is redefining the homeownership process from the ground up. We’re using technology to make it faster and more efficient, and humans to help make it friendly and enjoyable.`,
  },
  {
    name: 'Icon Savings Plan',
    shortDescription: `Become an investor in yourself. Build and grow your wealth by investing in a tax-advantaged retirement plan.`,
    icon: ICONS.iconSavingPlan,
    url: 'https://www.iconsavingsplan.com/kinly/',
    title: '',
    logo: ICONS.iconSavingPlanLogo,
    banner: require('_assets/MarketplaceBanners/icon_saving_plan.png'),
    longDescription: `Reach your long-term wealth goals by investing in a personal retirement plan by Icon. Built with smart features that make it easy to save and stay on track. Your savings will be invested in a portfolio tailored to your needs with investments from leading providers like Vanguard and BlackRock. We manage your portfolio and take care of rebalancing and diversification. There’s no minimum required and no transaction fees. You can invest up to $6,000 in a tax-deductible plan. To get started we’ll ask you a few questions, it takes about 5 minutes.`,
  },
  {
    name: 'Jerry - Auto Insurance',
    shortDescription: `Stop overpaying and save an average of $876 a year on car insurance with Jerry, your personal insurance shopper`,
    icon: ICONS.jerry,
    url: 'https://getjerry.com/signup/shopfor?utm_source=pfirstboulevard&utm_campaign={campaignID}&clickID={click_ID}',
    title: '',
    logo: ICONS.jerryLogo,
    banner: require('_assets/MarketplaceBanners/jerry.png'),
    longDescription: `Did you know 77% of people are overpaying for car insurance? Jerry is a free app that lets you find savings with quotes from over 50 top insurance providers across the country. In 45 seconds, you could save $73 a month for the same or better coverage. Jerry will even cancel your old policy for you. The best part is, Jerry never sells any of your information. That means no spam phone calls or emails, just more money in your pocket. Sign up today to find savings.`,
  },
  {
    name: 'Savi',
    shortDescription: `The Savi Platform offered by SAVI is a unique tool to help student loan borrowers better understand their debt, optimize their repayment options, and enroll in the best plan for their financial needs.`,
    icon: ICONS.savi,
    url: 'https://firstboulevard.bysavi.com/',
    title: '',
    logo: ICONS.saviLogo,
    banner: require('_assets/MarketplaceBanners/savi.png'),
    longDescription: `Student loan policy experts, advocates, and borrowers founded Savi to help solve our country's student debt crisis. Regardless of how much debt you have and where you are in your repayment journey, Savi will be there to walk you through every step of the process to ensure you can achieve financial freedom. 
    What can Savi do for you?
    •Save you money on your monthly payments
    •Provide one-on-one customized support
    •Create a clear path to apply for student loan forgiveness, and more!
    We’re excited to have Savi as our new partner, don’t wait to take control of your student loans. Join Savi’s community
    today!`,
  },
  {
    name: 'UNest Advisers LLC - New Deal',
    shortDescription: `Invest in your child’s future goals — save for education, first car, house, wedding, or to help their financial security as an adult.`,
    icon: ICONS.unestAdvisers,
    url: 'https://unest.co/firstblvd/',
    title: '',
    logo: ICONS.unestAdvisersLogo,
    banner: require('_assets/MarketplaceBanners/unest.png'),
    longDescription: `UNest offers a tax-advantaged custodial account that allows you to save for more than just college. Unlike a 529 account, there are no penalties on early withdrawals if you use funds for the benefit of the child. UNest offers multiple investment options suited to your needs, annual tax benefits, easy access to your account (making it reachable from anywhere), a chance to earn extra money from brands you love via UNest Rewards, and a gifting feature, allowing those you love access to contribute to your child's future.`,
  },
  {
    name: 'Rocket Lawyer',
    shortDescription: `Legal made simple - All the legal help you need. Anytime. Anywhere.`,
    icon: ICONS.rocketLawyer,
    url: 'https://www.rocketlawyer.com/? transaction_id=102c549a292a2fa5a90fa16d3c59fc&affiliate_ref=1630',
    title: '',
    logo: ICONS.rocketLawyerLogo,
    banner: require('_assets/MarketplaceBanners/rocket_lawyer.png'),
    longDescription: `Rocket Lawyer has helped over 20 million businesses, families and individuals make legal documents, get attorney advice, and confidently protect their futures. 50,000,000+ documents created* 240,000+ legal questions answered 2,000,000+ businesses served About Rocket Lawyer Rocket Lawyer believes everyone deserves access to affordable and simple legal services. Since 2008, they’ve helped over 17 million businesses, families and individuals make legal documents, get attorney advice, and confidently protect their futures. From easy legal documents and business incorporation, to discounted rates with outstanding lawyers, they are there to help every step of the way.`,
  },
  {
    name: 'Self',
    shortDescription: `Over 1.5-million people are using Self to build their credit scores Headline.`,
    icon: ICONS.self,
    url: 'self-lender.3qcw.net/ZdmZYW',
    title: '',
    logo: ICONS.selfLogo,
    banner: require('_assets/MarketplaceBanners/rocket_lawyer.png'),
    longDescription: `Did you know that payment history makes up 35% of your credit score? If you’ve never taken out a loan or had a credit card, it can be extremely frustrating when you find yourself in a position where you need your credit checked. That’s where Self is making a difference for millions of people. With Self, you can open a Credit Builder account and make regular monthly payments to build your credit score with three major bureaus. It’s a convenient, straightforward way to build credit — and according to the thousands of positive reviews, it really works.`,
  },
  {
    name: 'Trust & Will',
    shortDescription: `Covering your family's future is easy & affordable with Trust & Will. Get 10% off your Will, Trust, or Guardianship.`,
    icon: ICONS.trustandwill,
    url: 'https://trustandwill.com/?utm_source=kinly',
    title: '',
    logo: ICONS.trustAndWillLogo,
    banner: require('_assets/MarketplaceBanners/trust_will.png'),
    longDescription: `Trust & Will is the leading online estate planning platform whose mission is to help as many families as possible have a plan in place for the future. Prepare for the unexpected today by creating your Will, Trust or Nomination of Guardianship. With an Estate Plan in place, you can rest assured that your family and legacy are covered.`,
  },
  {
    name: 'Haven Life',
    shortDescription: `Haven Life offers an easy way to digitally purchase a dependable and affordable term life insurance policy to help financially protect the people you love.`,
    icon: ICONS.havenLife,
    url: 'https://havenlife.com/quick-quote?utm_source=firstboulevard&utm_medium=partner&utm_campaign=landingpage',
    title: '',
    logo: ICONS.havenLifeLogo,
    banner: require('_assets/MarketplaceBanners/haven_life.png'),
    longDescription: `Haven Life makes buying quality term life insurance actually simple. Here’s how:
    ● It’s easy: Apply online from your phone or computer
    ● It’s affordable: a 20-year, $250,000 term life insurance policy for a healthy, non-smoking 35-year-old woman can be as low as $14/month
    ● It’s dependable: The Haven Term policy is issued by MassMutual, a leading life insurer
    ● It’s more than just a monthly bill: Haven Life Plus, a rider to the Haven Term policy, provides policyholders in eligible states with access to additional benefits, like an online will service, at no cost. See benefits.`,
  },
];
